language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - pip install -U pip mock flake8 coverage coveralls
script:
    - flake8 .
    - coverage run --source=pdc_release_migration_tool setup.py test
after_success:
    - coveralls
